
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.4/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:1 (PROJECT)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.4/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:1 (PROJECT)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Users/z'b'w/bin/"
      - "E:/git/Git/mingw64/bin/"
      - "E:/git/Git/usr/local/bin/"
      - "E:/git/Git/usr/bin/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "D:/VS code/Scripts/"
      - "D:/VS code/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/Wolfram Research/WolframScript/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "C:/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/150/DTS/Binn/"
      - "C:/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/"
      - "D:/VS code/Microsoft VS Codemingw64/bin/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/"
      - "E:/git/Git/cmd/"
      - "E:/MATLAB/runtime/win64/"
      - "E:/MATLAB/bin/"
      - "C:/Program Files/CMake/bin/"
      - "E:/texlive/2026/bin/windows/"
      - "D:/Python0/Scripts/"
      - "D:/Python0/"
      - "C:/Users/z'b'w/AppData/Local/Microsoft/WindowsApps/"
      - "D:/\u8128\u8117\u9646\u7bd3\u8126\u811b\u5f55\u9541\u5f55\u8128/miktex/bin/x64/"
      - "C:/Users/z'b'w/AppData/Local/Programs/MiKTeX/miktex/bin/x64/"
      - "D:/VS code/Microsoft VS Code/mingw64/bin/"
      - "C:/Users/z'b'w/AppData/Roaming/Programs/Zero Install/"
      - "C:/Users/z'b'w/AppData/Local/Microsoft/Wi/"
      - "E:/git/Git/usr/bin/vendor_perl/"
      - "E:/git/Git/usr/bin/core_perl/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Users/z'b'w/bin/mingw32-make.exe.com"
      - "C:/Users/z'b'w/bin/mingw32-make.exe"
      - "E:/git/Git/mingw64/bin/mingw32-make.exe.com"
      - "E:/git/Git/mingw64/bin/mingw32-make.exe"
      - "E:/git/Git/usr/local/bin/mingw32-make.exe.com"
      - "E:/git/Git/usr/local/bin/mingw32-make.exe"
      - "E:/git/Git/usr/bin/mingw32-make.exe.com"
      - "E:/git/Git/usr/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe"
      - "D:/VS code/Scripts/mingw32-make.exe.com"
      - "D:/VS code/Scripts/mingw32-make.exe"
      - "D:/VS code/mingw32-make.exe.com"
      - "D:/VS code/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files (x86)/Wolfram Research/WolframScript/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Wolfram Research/WolframScript/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/mingw32-make.exe"
      - "C:/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn/mingw32-make.exe"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/mingw32-make.exe"
      - "C:/Program Files/Microsoft SQL Server/150/DTS/Binn/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft SQL Server/150/DTS/Binn/mingw32-make.exe"
      - "C:/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/mingw32-make.exe"
      - "D:/VS code/Microsoft VS Codemingw64/bin/mingw32-make.exe.com"
      - "D:/VS code/Microsoft VS Codemingw64/bin/mingw32-make.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/mingw32-make.exe.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA app/NvDLISR/mingw32-make.exe"
      - "E:/git/Git/cmd/mingw32-make.exe.com"
      - "E:/git/Git/cmd/mingw32-make.exe"
      - "E:/MATLAB/runtime/win64/mingw32-make.exe.com"
      - "E:/MATLAB/runtime/win64/mingw32-make.exe"
      - "E:/MATLAB/bin/mingw32-make.exe.com"
      - "E:/MATLAB/bin/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "E:/texlive/2026/bin/windows/mingw32-make.exe.com"
      - "E:/texlive/2026/bin/windows/mingw32-make.exe"
      - "D:/Python0/Scripts/mingw32-make.exe.com"
      - "D:/Python0/Scripts/mingw32-make.exe"
      - "D:/Python0/mingw32-make.exe.com"
      - "D:/Python0/mingw32-make.exe"
      - "C:/Users/z'b'w/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/z'b'w/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "D:/\u8128\u8117\u9646\u7bd3\u8126\u811b\u5f55\u9541\u5f55\u8128/miktex/bin/x64/mingw32-make.exe.com"
      - "D:/\u8128\u8117\u9646\u7bd3\u8126\u811b\u5f55\u9541\u5f55\u8128/miktex/bin/x64/mingw32-make.exe"
      - "C:/Users/z'b'w/AppData/Local/Programs/MiKTeX/miktex/bin/x64/mingw32-make.exe.com"
      - "C:/Users/z'b'w/AppData/Local/Programs/MiKTeX/miktex/bin/x64/mingw32-make.exe"
      - "D:/VS code/Microsoft VS Code/mingw64/bin/mingw32-make.exe.com"
      - "D:/VS code/Microsoft VS Code/mingw64/bin/mingw32-make.exe"
      - "C:/Users/z'b'w/AppData/Roaming/Programs/Zero Install/mingw32-make.exe.com"
      - "C:/Users/z'b'w/AppData/Roaming/Programs/Zero Install/mingw32-make.exe"
      - "C:/Users/z'b'w/AppData/Local/Microsoft/Wi/mingw32-make.exe.com"
      - "C:/Users/z'b'w/AppData/Local/Microsoft/Wi/mingw32-make.exe"
      - "E:/git/Git/usr/bin/vendor_perl/mingw32-make.exe.com"
      - "E:/git/Git/usr/bin/vendor_perl/mingw32-make.exe"
      - "E:/git/Git/usr/bin/core_perl/mingw32-make.exe.com"
      - "E:/git/Git/usr/bin/core_perl/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\z'b'w\\bin"
        - "E:\\git\\Git\\mingw64\\bin"
        - "E:\\git\\Git\\usr\\local\\bin"
        - "E:\\git\\Git\\usr\\bin"
        - "E:\\git\\Git\\usr\\bin"
        - "E:\\git\\Git\\mingw64\\bin"
        - "E:\\git\\Git\\usr\\bin"
        - "C:\\Users\\z'b'w\\bin"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "D:\\VS code\\Scripts"
        - "D:\\VS code"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0"
        - "C:\\WINDOWS\\System32\\OpenSSH"
        - "C:\\Program Files (x86)\\Wolfram Research\\WolframScript"
        - "C:\\Program Files\\dotnet"
        - "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn"
        - "C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\Binn"
        - "C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn"
        - "C:\\Program Files\\Microsoft SQL Server\\150\\DTS\\Binn"
        - "C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit"
        - "D:\\VS code\\Microsoft VS Codemingw64\\bin"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0"
        - "C:\\WINDOWS\\System32\\OpenSSH"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA app\\NvDLISR"
        - "E:\\git\\Git\\cmd"
        - "E:\\MATLAB\\runtime\\win64"
        - "E:\\MATLAB\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "E:\\texlive\\2026\\bin\\windows"
        - "D:\\Python0\\Scripts"
        - "D:\\Python0"
        - "C:\\Users\\z'b'w\\AppData\\Local\\Microsoft\\WindowsApps"
        - "D:\\\u8128\u8117\u9646\u7bd3\u8126\u811b\u5f55\u9541\u5f55\u8128\\miktex\\bin\\x64"
        - "C:\\Users\\z'b'w\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64"
        - "D:\\VS code\\Microsoft VS Code\\mingw64\\bin"
        - "C:\\Users\\z'b'w\\AppData\\Roaming\\Programs\\Zero Install"
        - "C:\\Users\\z'b'w\\AppData\\Local\\Microsoft\\Wi"
        - "E:\\git\\Git\\usr\\bin\\vendor_perl"
        - "E:\\git\\Git\\usr\\bin\\core_perl"
...
